export type ScanItemId = 'basic info'
| 'shield power'
| 'shield vulnerability'
| 'engine power'
| 'engine vulnerability'
| 'weapon power'
| 'weapon vulnerability'
| 'sensor power'
| 'sensor vulnerability'
| 'fake extra 1'
| 'fake extra 2'
| 'fake extra 3'
| 'fake extra 4'
| 'fake extra 5'
| 'fake extra 6'
| 'fake extra 7'
